name: "Lint and Fix Errors Automatically"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC

jobs:
  lint-fix:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository so we can work with the code
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      # Set up Node.js (adjust the node-version as needed)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Install project dependencies
      - name: Install dependencies
        run: npm install

      # Run the linter in fix mode. Ensure your package.json has a "lint:fix" script.
      - name: Run linter and auto-fix errors
        run: npm run lint:fix

      # Check to see if any files have been modified after running the linter
      - name: Check for changes
        id: git_diff
        run: |
          git diff --exit-code || echo "::set-output name=changed::true"

      # If changes are detected, commit them
      - name: Commit auto-fix changes
        if: steps.git_diff.outputs.changed == 'true'
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Auto-fixed lint errors" || echo "No changes to commit"
          
      # Push the changes back to the repository
      - name: Push changes
        if: steps.git_diff.outputs.changed == 'true'
        run: git push
